[project]
name = "integrationhh"
version = "0.1.0"
description = ""
authors = [
    {name = "Anton",email = "spaike77@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^6.1.1"
requests = "^2.32.3"

